// <auto-generated />
using System;
using DaviCodes.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DaviCodes.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DaviCodes.Entities.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("DisplayNameFK")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserFK")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayNameFK")
                        .IsUnique();

                    b.HasIndex("UserFK");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("DaviCodes.Entities.DisplayName", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Name");

                    b.ToTable("DisplayNames");
                });

            modelBuilder.Entity("DaviCodes.Entities.Hwid", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserFK")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserFK");

                    b.ToTable("Hwids");
                });

            modelBuilder.Entity("DaviCodes.Entities.Ip", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserFK")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserFK");

                    b.ToTable("Ips");
                });

            modelBuilder.Entity("DaviCodes.Entities.UsedDisplayName", b =>
                {
                    b.Property<string>("AccountFK")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("DisplayNameFK")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastUsage")
                        .HasColumnType("datetime(6)");

                    b.HasKey("AccountFK", "DisplayNameFK");

                    b.HasIndex("DisplayNameFK");

                    b.ToTable("UsedDisplayNames");
                });

            modelBuilder.Entity("DaviCodes.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DaviCodes.Entities.Account", b =>
                {
                    b.HasOne("DaviCodes.Entities.DisplayName", "CurrentDisplayName")
                        .WithOne("CurrentAccount")
                        .HasForeignKey("DaviCodes.Entities.Account", "DisplayNameFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DaviCodes.Entities.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentDisplayName");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DaviCodes.Entities.Hwid", b =>
                {
                    b.HasOne("DaviCodes.Entities.User", "User")
                        .WithMany("KnownHWIDs")
                        .HasForeignKey("UserFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DaviCodes.Entities.Ip", b =>
                {
                    b.HasOne("DaviCodes.Entities.User", "User")
                        .WithMany("KnownIPs")
                        .HasForeignKey("UserFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DaviCodes.Entities.UsedDisplayName", b =>
                {
                    b.HasOne("DaviCodes.Entities.Account", "Account")
                        .WithMany("DisplayNameHistory")
                        .HasForeignKey("AccountFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DaviCodes.Entities.DisplayName", "DisplayName")
                        .WithMany("HasBeenUsedBy")
                        .HasForeignKey("DisplayNameFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("DisplayName");
                });

            modelBuilder.Entity("DaviCodes.Entities.Account", b =>
                {
                    b.Navigation("DisplayNameHistory");
                });

            modelBuilder.Entity("DaviCodes.Entities.DisplayName", b =>
                {
                    b.Navigation("CurrentAccount");

                    b.Navigation("HasBeenUsedBy");
                });

            modelBuilder.Entity("DaviCodes.Entities.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("KnownHWIDs");

                    b.Navigation("KnownIPs");
                });
#pragma warning restore 612, 618
        }
    }
}
